# Generated by Django 4.2.7 on 2023-11-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_person_rename_department_course_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
