# Generated by Django 4.2.7 on 2023-11-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_person_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='course',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='department',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
